apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openstatus-oidc-secret
  namespace: observability
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    - secretKey: OIDC_ISSUER
      remoteRef:
        key: /OpenStatus/OIDC_ISSUER
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: /OpenStatus/OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: /OpenStatus/OIDC_CLIENT_SECRET
    - secretKey: OIDC_DISPLAY_NAME
      remoteRef:
        key: /OpenStatus/OIDC_DISPLAY_NAME
