apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openstatus-secret
  namespace: observability
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    - secretKey: AUTH_SECRET
      remoteRef:
        key: /OpenStatus/AUTH_SECRET
    - secretKey: CRON_SECRET
      remoteRef:
        key: /OpenStatus/CRON_SECRET
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: /OpenStatus/RESEND_API_KEY
