apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - external-secret.yaml
  - pvc.yaml
  - libsql-deployment.yaml
  - libsql-service.yaml
  - server-deployment.yaml
  - server-service.yaml
  - private-location-deployment.yaml
  - private-location-service.yaml
  - dashboard-deployment.yaml
  - dashboard-service.yaml
  - status-page-deployment.yaml
  - status-page-service.yaml
  - dashboard-ingress.yaml
  - status-page-ingress.yaml
