apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openstatus-libsql-pvc
  namespace: observability
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
  volumeName: pvc-b6b7eea2-963f-4be7-96a3-bddfe6225437
