apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openstatus-libsql-pvc
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
