apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openstatus-status-page-ingress
  namespace: observability
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$request_uri"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.status.realtong.cn"
      secretName: wildcard-status-realtong-cn-tls
  rules:
    - host: "*.status.realtong.cn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openstatus-status-page
                port:
                  number: 3000
