apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-sh-export
  namespace: homelab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
