apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acme-sh-secret
  namespace: homelab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    - secretKey: CF_Token
      remoteRef:
        key: /AcmeSh/CF_Token
    - secretKey: CF_Zone_ID
      remoteRef:
        key: /AcmeSh/CF_Zone_ID
    - secretKey: ACME_EMAIL
      remoteRef:
        key: /AcmeSh/ACME_EMAIL
