apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secret
  namespace: homelab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: /Vaultwarden/ADMIN_TOKEN
    - secretKey: SSO_CLIENT_ID
      remoteRef:
        key: /Vaultwarden/SSO_CLIENT_ID
    - secretKey: SSO_CLIENT_SECRET
      remoteRef:
        key: /Vaultwarden/SSO_CLIENT_SECRET