apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: homelab
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 256Mi
  volumeName: pvc-e633e54f-b691-43a9-822a-27c5ef142eed
  volumeMode: Filesystem
