apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synology-media-proxy-ingress
  namespace: homelab
  annotations:
    cert-manager.io/cluster-issuer: mkcert-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mp.wst.sh
      secretName: mp-wst-sh-tls
    - hosts:
        - emby.wst.sh
      secretName: emby-wst-sh-tls
  rules:
    - host: mp.wst.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moviepilot-external
                port:
                  number: 13000
    - host: emby.wst.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emby-external
                port:
                  number: 28096
