apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synology-media-proxy-ingress
  namespace: homelab
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mp.realtong.cn
    - hosts:
        - emby.realtong.cn
  rules:
    - host: mp.realtong.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moviepilot-external
                port:
                  number: 13000
    - host: emby.realtong.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emby-external
                port:
                  number: 28096
