apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
  namespace: homelab
data:
  config.yaml.tmpl: |
    server_url: https://headscale.realtong.cn
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090
    grpc_listen_addr: 127.0.0.1:50443
    grpc_allow_insecure: false

    noise:
      private_key_path: /var/lib/headscale/noise_private.key

    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48
      allocation: sequential

    derp:
      server:
        enabled: false
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      paths: []
      auto_update_enabled: true
      update_frequency: 24h

    disable_check_updates: false
    ephemeral_node_inactivity_timeout: 30m

    database:
      type: sqlite
      debug: false
      sqlite:
        path: /var/lib/headscale/db.sqlite
        write_ahead_log: true

    unix_socket: /var/run/headscale/headscale.sock
    unix_socket_permission: "0770"

    policy:
      mode: database
      path: ""

    oidc:
      only_start_if_oidc_is_available: true
      issuer: "__OIDC_ISSUER__"
      client_id: "__OIDC_CLIENT_ID__"
      client_secret_path: /etc/headscale/oidc-secrets/OIDC_CLIENT_SECRET
      scope: ["openid", "profile", "email"]
      email_verified_required: false
      pkce:
        enabled: true
        method: S256

    dns:
      magic_dns: true
      base_domain: tailnet.realtong.cn
      override_local_dns: true
      nameservers:
        global:
          - 1.1.1.1
          - 1.0.0.1
          - 2606:4700:4700::1111
          - 2606:4700:4700::1001
      search_domains: []
