apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headplane-secret
  namespace: homelab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    - secretKey: HEADPLANE_SERVER__COOKIE_SECRET
      remoteRef:
        key: /headscale/HEADPLANE_SERVER__COOKIE_SECRET
