apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headplane-secret
  namespace: homelab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    - secretKey: HEADPLANE_SERVER__COOKIE_SECRET
      remoteRef:
        key: /Headplane/HEADPLANE_SERVER__COOKIE_SECRET
    - secretKey: HEADPLANE_OIDC__ISSUER
      remoteRef:
        key: /Headplane/ISSUER
    - secretKey: HEADPLANE_OIDC__CLIENT_ID
      remoteRef:
        key: /Headplane/CLIENT_ID
    - secretKey: HEADPLANE_OIDC__CLIENT_SECRET
      remoteRef:
        key: /Headplane/CLIENT_SECRET
    - secretKey: HEADPLANE_HEADSCALE__API_KEY
      remoteRef:
        key: /Headplane/HEADSCALE_API_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headscale-secret
  namespace: homelab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    - secretKey: OIDC_ISSUER
      remoteRef:
        key: /headscale/ISSUER
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: /headscale/CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: /headscale/CLIENT_SECRET
