apiVersion: batch/v1
kind: Job
metadata:
  name: n8n-init-db
  namespace: homelab
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: postgres:16-alpine
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Waiting for PostgreSQL to be ready..."
              until PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres.databases.svc.cluster.local -U $POSTGRES_USER -d postgres -c '\q' 2>/dev/null; do
                echo "PostgreSQL is unavailable - sleeping"
                sleep 2
              done
              echo "PostgreSQL is up - executing init script"
              
              # Create database if not exists
              PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres.databases.svc.cluster.local -U $POSTGRES_USER -d postgres <<EOF
              SELECT 'CREATE DATABASE $DB_POSTGRESDB_DATABASE'
              WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$DB_POSTGRESDB_DATABASE')\gexec
              EOF
              
              # Create user if not exists
              PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres.databases.svc.cluster.local -U $POSTGRES_USER -d postgres <<EOF
              DO \$\$
              BEGIN
                IF NOT EXISTS (SELECT FROM pg_user WHERE usename = '$DB_POSTGRESDB_USER') THEN
                  CREATE USER $DB_POSTGRESDB_USER WITH PASSWORD '$DB_POSTGRESDB_PASSWORD';
                END IF;
              END
              \$\$;
              EOF
              
              # Grant privileges
              PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres.databases.svc.cluster.local -U $POSTGRES_USER -d postgres <<EOF
              GRANT ALL PRIVILEGES ON DATABASE $DB_POSTGRESDB_DATABASE TO $DB_POSTGRESDB_USER;
              ALTER DATABASE $DB_POSTGRESDB_DATABASE OWNER TO $DB_POSTGRESDB_USER;
              EOF
              
              # Create schema if specified and not public
              if [ "$DB_POSTGRESDB_SCHEMA" != "public" ]; then
                PGPASSWORD=$DB_POSTGRESDB_PASSWORD psql -h postgres.databases.svc.cluster.local -U $DB_POSTGRESDB_USER -d $DB_POSTGRESDB_DATABASE <<EOF
                CREATE SCHEMA IF NOT EXISTS $DB_POSTGRESDB_SCHEMA;
                GRANT ALL ON SCHEMA $DB_POSTGRESDB_SCHEMA TO $DB_POSTGRESDB_USER;
                EOF
              fi
              
              echo "Database initialization completed successfully"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: POSTGRES_ADMIN_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: POSTGRES_ADMIN_PASSWORD
            - name: DB_POSTGRESDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: DB_POSTGRESDB_DATABASE
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: DB_POSTGRESDB_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: DB_POSTGRESDB_PASSWORD
            - name: DB_POSTGRESDB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: DB_POSTGRESDB_SCHEMA
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

