apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: drizzle-gateway-secret
  namespace: databases
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    - secretKey: MASTERPASS
      remoteRef:
        key: /Drizzle-Gateway/MASTERPASS