apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drizzle-gateway-pvc
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client