apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drizzle-gateway-pvc
  namespace: databases
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  volumeName: pvc-6f5bfd56-a337-4026-acb5-d58ec1f5fe3d
  volumeMode: Filesystem
