apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cli-proxy-api-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client
