apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: afilmory-ingress
  namespace: homelab
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - art.realtong.cn
  rules:
    - host: art.realtong.cn
      http:
        paths:
          - path: /photos/[^/.]+$
            pathType: ImplementationSpecific
            backend:
              service:
                name: afilmory
                port:
                  number: 3000
          - path: /photos(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: afilmory
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: afilmory
                port:
                  number: 3000
