apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: neko-master-secret
  namespace: homelab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    - secretKey: COOKIE_SECRET
      remoteRef:
        key: /neko-master/COOKIE_SECRET
    - secretKey: CH_DATABASE
      remoteRef:
        key: /neko-master/CH_DATABASE
    - secretKey: CH_USER
      remoteRef:
        key: /neko-master/CH_USER
    - secretKey: CH_PASSWORD
      remoteRef:
        key: /neko-master/CH_PASSWORD
