apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neko-master-data-pvc
  namespace: homelab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
  volumeName: pvc-278ba20c-9409-475b-9bfc-7d5d404e7efe
