apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multica-postgres-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
