apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multica-uploads-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
