apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: homelab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_URL: "postgresql://immich:{{ .POSTGRES_PASSWORD | urlquery }}@immich-postgres.databases.svc.cluster.local:5432/immich"
        REDIS_URL: "redis://:{{ .REDIS_PASSWORD | urlquery }}@redis.databases.svc.cluster.local:6379/15"
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /immich/POSTGRES_PASSWORD
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: /Redis/REDIS_PASSWORD
