apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresus
  namespace: databases
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresus
      version: "2.6.0"
      sourceRef:
        kind: HelmRepository
        name: postgresus-repository
        namespace: flux-system
  values:
    customRootCA: my-root-ca
    persistence:
      enabled: true
      storageClassName: nfs-client
      size: 20Gi
      accessModes: ReadWriteMany
    ingress:
      enabled: true
      annotations:
      hosts:
        - host: dbb.wst.sh
          paths:
            - path: /
              pathType: Prefix