apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kite-secret
  namespace: observability
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    - secretKey: DB_DSN
      remoteRef:
        key: /Kite/DB_DSN
    - secretKey: JWT_SECRET
      remoteRef:
        key: /Kite/JWT_SECRET
    - secretKey: KITE_ENCRYPT_KEY
      remoteRef:
        key: /Kite/KITE_ENCRYPT_KEY