apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nine-router-ingress
  namespace: homelab
  annotations:
    glance/icon: simple-icons:openai
    glance/name: "9Router"
    glance/url: "https://9router.realtong.cn"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - 9router.realtong.cn
  rules:
    - host: 9router.realtong.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nine-router
                port:
                  number: 20128
