apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  path: ./infrastructure/controllers 
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true