apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui-secret
  namespace: homelab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    - secretKey: QUI__SESSION_SECRET
      remoteRef:
        key: /Qui/QUI__SESSION_SECRET
    - secretKey: QUI__OIDC_CLIENT_ID
      remoteRef:
        key: /Qui/QUI__OIDC_CLIENT_ID
    - secretKey: QUI__OIDC_CLIENT_SECRET
      remoteRef:
        key: /Qui/QUI__OIDC_CLIENT_SECRET
    - secretKey: QUI__OIDC_ISSUER
      remoteRef:
        key: /Qui/QUI__OIDC_ISSUER
