apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-pvc
  namespace: auth
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 256Mi