apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-pvc
  namespace: auth
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 256Mi
  volumeName: pvc-f3a12adc-0b64-4207-8fb9-61512aa5e895
