apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-automation-proxy-ingress
  namespace: homelab
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://tinyauth.auth.svc.cluster.local:3000/api/auth/nginx"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.realtong.cn/login"
    nginx.ingress.kubernetes.io/auth-signin-redirect-param: redirect_uri
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - movie.realtong.cn
    - hosts:
        - tv.realtong.cn
    - hosts:
        - pt.realtong.cn
  rules:
    - host: movie.realtong.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr-external
                port:
                  number: 17878
    - host: tv.realtong.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr-external
                port:
                  number: 18989
    - host: pt.realtong.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prowlarr-external
                port:
                  number: 19696
