apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clash-master-data
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
