apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: databases
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: /Postgres/POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: /Postgres/POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /Postgres/POSTGRES_PASSWORD