apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-home-credentials
  namespace: external-dns
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: adguard-home-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ADGUARD_HOME_USER
      remoteRef:
        key: /AdGuardHome/USERNAME
    - secretKey: ADGUARD_HOME_PASS
      remoteRef:
        key: /AdGuardHome/PASSWORD
