apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer
  namespace: observability
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portainer-kubernetes-view
rules:
  - nonResourceURLs:
      - /version
    verbs: ["get"]
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: portainer
    namespace: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer-kubernetes-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: portainer-kubernetes-view
subjects:
  - kind: ServiceAccount
    name: portainer
    namespace: observability
