apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sub2api-secret
  namespace: homelab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: sub2api-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: Sub2API/POSTGRES_PASSWORD
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: Sub2API/ADMIN_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: Sub2API/JWT_SECRET
    - secretKey: TOTP_ENCRYPTION_KEY
      remoteRef:
        key: Sub2API/TOTP_ENCRYPTION_KEY
