apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sub2api-secret
  namespace: homelab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    # Database configuration
    - secretKey: DB_POSTGRESDB_DATABASE
      remoteRef:
        key: /sub2api/DB_POSTGRESDB_DATABASE
    - secretKey: DB_POSTGRESDB_USER
      remoteRef:
        key: /sub2api/DB_POSTGRESDB_USER
    - secretKey: DB_POSTGRESDB_PASSWORD
      remoteRef:
        key: /sub2api/DB_POSTGRESDB_PASSWORD

    # Application configuration
    - secretKey: RUN_MODE
      remoteRef:
        key: /sub2api/RUN_MODE
    - secretKey: SIMPLE_MODE_CONFIRM
      remoteRef:
        key: /sub2api/SIMPLE_MODE_CONFIRM
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: /sub2api/ADMIN_USERNAME
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: /sub2api/ADMIN_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: /sub2api/JWT_SECRET

    # Security configuration
    - secretKey: SECURITY_URL_ALLOWLIST_ENABLED
      remoteRef:
        key: /sub2api/SECURITY_URL_ALLOWLIST_ENABLED

    # Postgres admin credentials for database initialization
    - secretKey: POSTGRES_ADMIN_USER
      remoteRef:
        key: /Postgres/POSTGRES_USER
    - secretKey: POSTGRES_ADMIN_PASSWORD
      remoteRef:
        key: /Postgres/POSTGRES_PASSWORD
