apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sub2api-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
