apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sub2api-redis-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
