apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./_namespaces/
  - ./pocket-id/
  - ./tinyauth/
  - ./grafana/
  - ./kite/
  - ./beszel-hub/
  - ./glance/
  - ./prometheus/
  - ./glance-k8s/
  - ./openstatus/
  - ./kube-state-metrics/
  - ./portainer/
  - ./vaultwarden/
  - ./drizzle-gateway/
  - ./postgres/
  - ./redis/
  - ./manifest/
  - ./asspp/
  - ./portfolio-ibkr/
  - ./clickhouse/
  - ./neko-master/
  - ./synology-media-proxy/
  - ./media-automation-proxy/
  - ./ep-proxy/
  - ./homeassistant/
  - ./adguard-home/
  - ./openwrt/
  - ./pve/
  - ./qui/
  - ./immich/
  - ./multica/
  - ./sub2api/
