apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: databases
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
  volumeName: pvc-e9b0e9d3-0c06-498d-80b9-693165fcd363
  volumeMode: Filesystem
