apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: databases
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      nodeSelector:
        kubernetes.io/hostname: "realtong-server"
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: native
          env:
            - name: CLICKHOUSE_DB
              valueFrom:
                secretKeyRef:
                  name: neko-master-clickhouse-secret
                  key: CH_DATABASE
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: neko-master-clickhouse-secret
                  key: CH_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neko-master-clickhouse-secret
                  key: CH_PASSWORD
            - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
              value: "1"
          readinessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1500m
              memory: 2Gi
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
  volumeClaimTemplates:
    - metadata:
        name: clickhouse-data
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: nfs-client
        resources:
          requests:
            storage: 20Gi
