apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: observability
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
  volumeName: pvc-f7089f71-7fb2-42d9-947b-83dbcd7c129a
  volumeMode: Filesystem
