apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portfolio-ibkr-secret
  namespace: homelab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  data:
    - secretKey: IBKR_ACCOUNT_ID
      remoteRef:
        key: /PortfolioIBKR/IBKR_ACCOUNT_ID
    - secretKey: OAUTH_JSON
      remoteRef:
        key: /PortfolioIBKR/OAUTH_JSON
