apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portfolio-ibkr-data
  namespace: homelab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
