apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird
  namespace: netbird
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/netbird
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: netbird
        namespace: netbird
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    namespace: netbird
    
    dashboard:
      enabled: true
      ingress:
        enabled: false
    
    management:
      type: deployment
      configmap: |
        {
          "DATABASE_TYPE": "postgres",
          "DATABASE_URL": "postgresql://netbird:RealTong233.@postgresus.databases.svc:5432/netbird?sslmode=disable",
          "MANAGEMENT_URL": "https://netbird.wst.sh",
          "METRICS_URL": "http://netbird-management:9090",
          "CERT_MANAGER_ENABLED": true,
          "CERT_MANAGER_CLUSTER_ISSUER": "mkcert-issuer",
          "SINGLE_ACCOUNT_MODE_DOMAIN": "netbird.selfhosted",
          "DNS_DOMAIN": "netbird.selfhosted",
          "ENABLE_USER_ENDPOINT_GROUPS": false,
          "ENABLE_GROUP_PROPAGATION": false,
          "ENABLE_SINGLE_ACCOUNT_MODE": false,
          "TURN_PORT_RANGE_START": 50000,
          "TURN_PORT_RANGE_END": 60000,
          "TURN_MIN_SECRET": "RealTong233.",
          "TURN_MAX_SECRET": "RealTong233.",
          "REDIS_URL": "redis://redis.databases.svc:6379",
          "REDIS_PASSWORD": "",
          "JWT_SECRET": "isLvGvmveNCP51H+/BJlQ9fUXbF6QkI1ENMY0sivfEg="
        }
        
    signal:
      type: deployment
      replicaCount: 1
    
    turn:
      type: deployment
      replicaCount: 1
    
    postgresql:
      enabled: false
    
    redis:
      enabled: false
