apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird
  namespace: netbird
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/netbird
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: netbird
        namespace: netbird
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    namespace: netbird
    
    dashboard:
      enabled: true
      ingress:
        enabled: false
      env:
        NETBIRD_MGMT_API_ENDPOINT: "https://netbird.wst.sh"
        NETBIRD_MGMT_GRPC_API_ENDPOINT: "https://netbird.wst.sh"
        NETBIRD_MGMT_CERT_FILE: "/etc/netbird/certs/wildcard.wst.sh.crt"
        NETBIRD_MGMT_CERT_KEY_FILE: "/etc/netbird/certs/wildcard.wst.sh.key"
        LETSENCRYPT_DOMAIN: "none"
    
    management:
      enabled: true
      type: deployment
      podCommand:
        args:
          - --port=80
          - --log-file=console
          - --log-level=info
          - --disable-anonymous-metrics=false
          - --single-account-mode-domain=netbird.selfhosted
          - --dns-domain=netbird.selfhosted
      env:
        NETBIRD_STORE_ENGINE_POSTGRES_DSN: "postgresql://netbird:RealTong233.@postgresus.databases.svc:5432/netbird?sslmode=disable"
        NETBIRD_DATABASE_TYPE: "postgres"
        NETBIRD_JWT_SECRET: "isLvGvmveNCP51H+/BJlQ9fUXbF6QkI1ENMY0sivfEg="
        NETBIRD_TURN_MIN_SECRET: "RealTong233."
        NETBIRD_TURN_MAX_SECRET: "RealTong233."
        NETBIRD_SIGNAL_ADDRESS: "signal.netbird.wst.sh:443"
        NETBIRD_RELAY_ADDRESS: "relay.netbird.wst.sh:443"
        NETBIRD_TURN_PORT_START: "50000"
        NETBIRD_TURN_PORT_END: "60000"
        NETBIRD_REDIS_URL: "redis://redis.databases.svc:6379"
        NB_CERT_MANAGER_ENABLED: "true"
        NB_CERT_MANAGER_CLUSTER_ISSUER: "mkcert-issuer"
      envFromSecret:
        NETBIRD_STORE_ENGINE_POSTGRES_DSN: "netbird-creds/NB_DATABASE_URL"
        NETBIRD_JWT_SECRET: "netbird-creds/NB_MANAGEMENT_JWT_SECRET"
        NETBIRD_TURN_MIN_SECRET: "netbird-creds/NB_TURN_MIN_SECRET"
        NETBIRD_TURN_MAX_SECRET: "netbird-creds/NB_TURN_MAX_SECRET"
        
    signal:
      enabled: true
      type: deployment
      replicaCount: 1
    
    relay:
      enabled: true
      replicaCount: 1
    
    postgresql:
      enabled: false
    
    redis:
      enabled: false
