apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: manifest-secret
  namespace: homelab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: manifest-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://RealTong:{{ .POSTGRES_PASSWORD | urlquery }}@postgres.databases.svc.cluster.local:5432/manifest"
        BETTER_AUTH_URL: "https://ai.realtong.cn"
        BETTER_AUTH_SECRET: "{{ .BETTER_AUTH_SECRET }}"
  data:
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: manifest/BETTER_AUTH_SECRET
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: Postgres/POSTGRES_PASSWORD
