apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: manifest-secret
  namespace: homelab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: manifest-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://manifest:{{ .POSTGRES_PASSWORD | urlquery }}@manifest-postgres:5432/manifest"
        BETTER_AUTH_URL: "https://ai.realtong.cn"
  data:
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: /manifest/BETTER_AUTH_SECRET
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /manifest/POSTGRES_PASSWORD
