apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manifest-postgres-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
